#设置服务器端口
#server:
#    port:8085
#    address:localhost

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lesson
    username: wyn
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*/*.xml
  typeAliasesPackage: com.wyn.entity
#  mapper-locations: classpath:mapper/*.xml
#  mapper-locations: classpath:/resource/mapper/*.xml